allowBuilds:
  es5-ext: true
  esbuild: true
  svelte-preprocess: true
onlyBuiltDependencies:
  - esbuild
  - es5-ext
  - svelte-preprocess
overrides:
  esbuild: ^0.28.2
patchedDependencies:
  svelte-i18n@4.0.1: patches/svelte-i18n@4.0.1.patch
