"use client"

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react"
import type { CanonEntityReference } from "@/lib/relationships-canon"
import { redRisingDemo } from "./red-rising-demo-data"
import { redRisingAdditionalKnowledge } from "./red-rising-graph"

export type KnowledgeState = "known" | "believed" | "suspected" | "rumored" | "misunderstood" | "unknown" | "disputed"
export type KnowledgeRecord = { id: string; observerId: string; subject: CanonEntityReference; state: KnowledgeState; confidence?: string; awarenessTime?: string; discoveryMethod?: string; belief?: string; objectiveTruth?: string; visibility: "private" | "shared"; notes?: string; sourceIds: string[]; createdAt: number; updatedAt: number }
export type KnowledgeEdit = Partial<Pick<KnowledgeRecord, "observerId" | "subject" | "state" | "confidence" | "awarenessTime" | "discoveryMethod" | "belief" | "objectiveTruth" | "visibility" | "notes" | "sourceIds">>
type KnowledgeContextValue = { records: Record<string, KnowledgeRecord>; getRecord: (id: string | null | undefined) => KnowledgeRecord | null; addRecord: (patch: KnowledgeEdit) => string; updateRecord: (id: string, patch: KnowledgeEdit) => void; deleteRecord: (id: string) => void }
const STORAGE_KEY = "world-engine:canon-knowledge"; const KnowledgeContext = createContext<KnowledgeContextValue | null>(null)
function makeId(observerId: string, subject: CanonEntityReference, existing: Record<string, KnowledgeRecord>) { const base = `${observerId}-${subject.entityType}-${subject.entityId}`.toLowerCase().replace(/[^a-z0-9]+/g, "-"); let id = base; let suffix = 2; while (existing[id]) id = `${base}-${suffix++}`; return id }
export function KnowledgeCanonProvider({ children }: { children: ReactNode }) { const [records, setRecords] = useState<Record<string, KnowledgeRecord>>({ ...(redRisingDemo.knowledge as unknown as Record<string, KnowledgeRecord>), ...redRisingAdditionalKnowledge }); const [hydrated, setHydrated] = useState(false); useEffect(() => { try { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) setRecords(JSON.parse(saved) as Record<string, KnowledgeRecord>) } catch {} finally { setHydrated(true) } }, []); useEffect(() => { if (hydrated) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(records)) }, [hydrated, records]); const getRecord = useCallback((id: string | null | undefined) => id ? records[id] ?? null : null, [records]); const addRecord = useCallback((patch: KnowledgeEdit) => { const subject = patch.subject ?? { entityType: "concept", entityId: "" }; const id = makeId(patch.observerId ?? "character", subject, records); const now = Date.now(); setRecords((previous) => ({ ...previous, [id]: { id, observerId: patch.observerId ?? "", subject, state: patch.state ?? "known", confidence: patch.confidence, awarenessTime: patch.awarenessTime, discoveryMethod: patch.discoveryMethod, belief: patch.belief, objectiveTruth: patch.objectiveTruth, visibility: patch.visibility ?? "private", notes: patch.notes, sourceIds: patch.sourceIds ?? [], createdAt: now, updatedAt: now } })); return id }, [records]); const updateRecord = useCallback((id: string, patch: KnowledgeEdit) => setRecords((previous) => previous[id] ? { ...previous, [id]: { ...previous[id], ...patch, updatedAt: Date.now() } } : previous), []); const deleteRecord = useCallback((id: string) => setRecords((previous) => { const next = { ...previous }; delete next[id]; return next }), []); const value = useMemo(() => ({ records, getRecord, addRecord, updateRecord, deleteRecord }), [records, getRecord, addRecord, updateRecord, deleteRecord]); return <KnowledgeContext.Provider value={value}>{children}</KnowledgeContext.Provider> }
export function useKnowledgeCanon() { const context = useContext(KnowledgeContext); if (!context) throw new Error("useKnowledgeCanon must be used within KnowledgeCanonProvider"); return context }
