import type { CanonRelationship } from "./relationships-canon"
import type { KnowledgeRecord } from "./knowledge-canon"

const sourceIds = ["bookworm-red-rising", "red-rising-wiki"]

const relationship = (record: Omit<CanonRelationship, "createdAt" | "updatedAt" | "sourceIds">): CanonRelationship => ({
  ...record,
  sourceIds,
  createdAt: 10,
  updatedAt: 10,
})

export const redRisingAdditionalRelationships: Record<string, CanonRelationship> = {
  "fitchner-sevro": relationship({ id: "fitchner-sevro", subject: { entityType: "character", entityId: "fitchner" }, object: { entityType: "character", entityId: "sevro" }, label: "father and son", direction: "mutual", status: "historical", strength: "foundational", summary: "A secret parent-child relationship hidden behind rebellion and the Howlers.", history: "Fitchner's concealed identity changes how Sevro understands both his father and the Rising.", timeExpression: "Before and during the Rising", confidence: "high" }),
  "darrow-nero": relationship({ id: "darrow-nero", subject: { entityType: "character", entityId: "darrow" }, object: { entityType: "character", entityId: "nero" }, label: "protege and enemy", direction: "mutual", status: "broken", strength: "foundational", summary: "Nero mistakes the infiltrator for a useful Gold heir and later becomes one of Darrow's defining enemies.", history: "Mars politics and the Institute bind them together before the truth makes the relationship impossible.", timeExpression: "Institute through the fall of the Society", confidence: "high" }),
  "darrow-adrius": relationship({ id: "darrow-adrius", subject: { entityType: "character", entityId: "darrow" }, object: { entityType: "character", entityId: "adrius" }, label: "political enemies", direction: "mutual", status: "historical", strength: "foundational", summary: "Darrow and the Jackal understand one another as existential threats.", history: "Their rivalry moves from Institute competition to a struggle over the future of the Society.", timeExpression: "Institute through civil war", confidence: "high" }),
  "darrow-lysander": relationship({ id: "darrow-lysander", subject: { entityType: "character", entityId: "darrow" }, object: { entityType: "character", entityId: "lysander" }, label: "opposed claimants", direction: "mutual", status: "active", strength: "major", summary: "Their conflict is both military and ideological: republic against restored Gold legitimacy.", history: "Each carries a competing account of what should replace the Society.", timeExpression: "Post-Society Solar War", confidence: "high" }),
  "virginia-adrius": relationship({ id: "virginia-adrius", subject: { entityType: "character", entityId: "virginia" }, object: { entityType: "character", entityId: "adrius" }, label: "siblings and enemies", direction: "mutual", status: "broken", strength: "foundational", summary: "Their sibling relationship is poisoned by competing ideas of power, recognition, and control.", history: "Family intimacy becomes political leverage and eventually open opposition.", timeExpression: "Society era through Republic", confidence: "high" }),
  "virginia-lysander": relationship({ id: "virginia-lysander", subject: { entityType: "character", entityId: "virginia" }, object: { entityType: "character", entityId: "lysander" }, label: "rulers and ideological rivals", direction: "mutual", status: "active", strength: "major", summary: "Both claim a legitimate future for humanity, but one begins from republican citizenship and the other from Gold inheritance.", history: "Their conflict is mediated by family memory, diplomacy, and war.", timeExpression: "Solar Republic era", confidence: "high" }),
  "sevro-ephraim": relationship({ id: "sevro-ephraim", subject: { entityType: "character", entityId: "sevro" }, object: { entityType: "character", entityId: "ephraim" }, label: "family and strained allies", direction: "mutual", status: "active", strength: "major", summary: "Their relationship carries the weight of marriage, parenthood, rebellion, and grief.", history: "Ephraim's distance and Sevro's expectations make family loyalty painful rather than simple.", timeExpression: "After the first Rising", confidence: "high" }),
  "lyria-ephraim": relationship({ id: "lyria-ephraim", subject: { entityType: "character", entityId: "lyria" }, object: { entityType: "character", entityId: "ephraim" }, label: "reluctant partners", direction: "mutual", status: "historical", strength: "major", summary: "A survivor and a damaged veteran learn to act together despite mistrust.", history: "Their partnership reveals the distance between republican victory and lived liberation.", timeExpression: "Republic era", confidence: "high" }),
  "cassius-lysander": relationship({ id: "cassius-lysander", subject: { entityType: "character", entityId: "cassius" }, object: { entityType: "character", entityId: "lysander" }, label: "mentor and ward", direction: "mutual", status: "historical", strength: "foundational", summary: "Cassius becomes responsible for educating and protecting Lysander after the Society's collapse.", history: "The bond is both genuine care and a political inheritance.", timeExpression: "Between Society and Rim wars", confidence: "high" }),
  "cassius-darrow": relationship({ id: "cassius-darrow", subject: { entityType: "character", entityId: "cassius" }, object: { entityType: "character", entityId: "darrow" }, label: "dueling rivals and brothers-in-arms", direction: "mutual", status: "historical", strength: "major", summary: "Their respect grows through repeated betrayal, combat, and shared enemies.", history: "The relationship asks whether personal honor can survive political deception.", timeExpression: "Institute through late war", confidence: "high" }),
  "atalantia-ajax": relationship({ id: "atalantia-ajax", subject: { entityType: "character", entityId: "atalantia" }, object: { entityType: "character", entityId: "ajax" }, label: "commanders and kin", direction: "mutual", status: "historical", strength: "major", summary: "The Grimmus war machine binds family identity to military obedience.", history: "Their relationship is shaped by hardline Gold restoration.", timeExpression: "Solar War", confidence: "high" }),
  "diomedes-alexandar": relationship({ id: "diomedes-alexandar", subject: { entityType: "character", entityId: "diomedes" }, object: { entityType: "character", entityId: "alexandar" }, label: "Rim allies", direction: "mutual", status: "active", strength: "major", summary: "Their connection represents Rim solidarity against Core assumptions.", history: "Both navigate house duty, military command, and the possibility of a different political settlement.", timeExpression: "Rim conflict", confidence: "medium" }),
  "sons-fitchner": relationship({ id: "sons-fitchner", subject: { entityType: "organization", entityId: "sons-of-ares" }, object: { entityType: "character", entityId: "fitchner" }, label: "led by", direction: "directed", status: "historical", strength: "foundational", summary: "Fitchner's hidden leadership connects Gold access to the revolutionary network.", history: "The relationship makes the Rising an infiltration of institutions as well as a revolt from below.", timeExpression: "Before and during the first Rising", confidence: "high" }),
  "telemanus-pax": relationship({ id: "telemanus-pax", subject: { entityType: "organization", entityId: "house-telemanus" }, object: { entityType: "character", entityId: "pax" }, label: "family and inheritance", direction: "directed", status: "active", strength: "major", summary: "Pax carries the Telemanus name into a post-Society world.", history: "His future tests whether a Gold house can become a civic rather than hereditary institution.", timeExpression: "Republic era", confidence: "medium" }),
  "red-culture-mars": relationship({ id: "red-culture-mars", subject: { entityType: "culture", entityId: "reds" }, object: { entityType: "location", entityId: "mars" }, label: "originates in", direction: "directed", status: "active", strength: "foundational", summary: "The Martian mines shape Red work, family life, language, and resistance.", history: "The culture persists after liberation even as its relationship to Mars changes.", timeExpression: "Generations through Republic", confidence: "high" }),
  "institute-darrow": relationship({ id: "institute-darrow", subject: { entityType: "location", entityId: "institute" }, object: { entityType: "character", entityId: "darrow" }, label: "tests and transforms", direction: "directed", status: "historical", strength: "foundational", summary: "The Institute turns Darrow's disguise into leadership and political access.", history: "He enters as an infiltrator and leaves with genuine attachments and new enemies.", timeExpression: "Red Rising", confidence: "high" }),
}

const knowledge = (record: Omit<KnowledgeRecord, "createdAt" | "updatedAt" | "sourceIds">): KnowledgeRecord => ({ ...record, sourceIds, createdAt: 10, updatedAt: 10 })

export const redRisingAdditionalKnowledge: Record<string, KnowledgeRecord> = {
  "virginia-eo": knowledge({ id: "virginia-eo", observerId: "virginia", subject: { entityType: "character", entityId: "eo" }, state: "known", confidence: "high", awarenessTime: "Before the Institute", discoveryMethod: "Rebel intelligence and Darrow's account", belief: "Eo's death is part of the reason Darrow became who he is", objectiveTruth: "Eo's death catalyzes Darrow's recruitment", visibility: "private", notes: "Virginia must understand the personal history beneath Darrow's political identity." }),
  "sevro-fitchner": knowledge({ id: "sevro-fitchner", observerId: "sevro", subject: { entityType: "character", entityId: "fitchner" }, state: "known", confidence: "high", awarenessTime: "During the Rising", discoveryMethod: "Direct family revelation", belief: "Fitchner is both father and revolutionary leader", objectiveTruth: "Fitchner is Sevro's father and Ares", visibility: "private", notes: "Knowledge is emotionally loaded and strategically dangerous." }),
  "lysander-darrow": knowledge({ id: "lysander-darrow", observerId: "lysander", subject: { entityType: "character", entityId: "darrow" }, state: "known", confidence: "high", awarenessTime: "After the Institute and later war", discoveryMethod: "Political intelligence and direct conflict", belief: "Darrow is the central enemy of Gold restoration", objectiveTruth: "Darrow is a Red revolutionary and republican leader", visibility: "shared", notes: "The fact is known; its political meaning remains contested." }),
  "lysander-cassius": knowledge({ id: "lysander-cassius", observerId: "lysander", subject: { entityType: "character", entityId: "cassius" }, state: "known", confidence: "high", awarenessTime: "Childhood through mentorship", discoveryMethod: "Direct relationship", belief: "Cassius is both teacher and moral model", objectiveTruth: "Cassius is a flawed Gold warrior who chooses loyalty beyond dynasty", visibility: "private", notes: "Useful for testing relational knowledge rather than plot secrets." }),
  "adrius-virginia": knowledge({ id: "adrius-virginia", observerId: "adrius", subject: { entityType: "character", entityId: "virginia" }, state: "misunderstood", confidence: "high", awarenessTime: "Childhood", discoveryMethod: "Family rivalry and political interpretation", belief: "Virginia's compassion is weakness that can be exploited", objectiveTruth: "Virginia's empathy is paired with strategic discipline", visibility: "shared", notes: "A sibling misread becomes a political vulnerability." }),
  "nero-eo": knowledge({ id: "nero-eo", observerId: "nero", subject: { entityType: "character", entityId: "eo" }, state: "misunderstood", confidence: "medium", awarenessTime: "Before the Rising", discoveryMethod: "Society disciplinary record", belief: "Eo is an isolated dissenter", objectiveTruth: "Eo becomes a symbol whose meaning exceeds the individual", visibility: "shared", notes: "The state sees a local offense; the rebellion sees a founding memory." }),
  "ephraim-sevro": knowledge({ id: "ephraim-sevro", observerId: "ephraim", subject: { entityType: "character", entityId: "sevro" }, state: "known", confidence: "high", awarenessTime: "Before the Republic", discoveryMethod: "Marriage and family life", belief: "Sevro is brilliant, wounded, and in danger of becoming only a weapon", objectiveTruth: "Sevro is both revolutionary commander and parent", visibility: "private", notes: "Tests knowledge of emotional states and competing roles." }),
  "lyria-republic": knowledge({ id: "lyria-republic", observerId: "lyria", subject: { entityType: "organization", entityId: "solar-republic" }, state: "suspected", confidence: "medium", awarenessTime: "After liberation", discoveryMethod: "Personal experience with institutions", belief: "The Republic may repeat the Society's distance from ordinary people", objectiveTruth: "The Republic is genuinely different but incomplete and compromised", visibility: "private", notes: "A citizen's suspicion is not the same as an objective political verdict." }),
  "rim-society": knowledge({ id: "rim-society", observerId: "rim-houses", subject: { entityType: "organization", entityId: "society" }, state: "known", confidence: "high", awarenessTime: "Generational history", discoveryMethod: "House archives and inherited memory", belief: "The Core has repeatedly used Rim loyalty without respecting Rim autonomy", objectiveTruth: "Rim grievances are rooted in historical power imbalance", visibility: "shared", notes: "Useful for testing collective observer IDs." }),
  "pax-darrow": knowledge({ id: "pax-darrow", observerId: "pax", subject: { entityType: "character", entityId: "darrow" }, state: "believed", confidence: "medium", awarenessTime: "Childhood and political education", discoveryMethod: "Family testimony and public history", belief: "Darrow is both hero and dangerous inherited myth", objectiveTruth: "Darrow is a revolutionary leader whose legacy contains victory and harm", visibility: "shared", notes: "The next generation inherits a contested historical narrative." }),
  "gold-students-carving": knowledge({ id: "gold-students-carving", observerId: "gold-students", subject: { entityType: "concept", entityId: "carving" }, state: "rumored", confidence: "low", awarenessTime: "Institute period", discoveryMethod: "Whispered speculation", belief: "Carving is an impossible or legendary procedure", objectiveTruth: "Carving is advanced but real and politically controlled", visibility: "shared", notes: "Good rumor-state test with low confidence." }),
  "society-rebel-network": knowledge({ id: "society-rebel-network", observerId: "society", subject: { entityType: "organization", entityId: "sons-of-ares" }, state: "suspected", confidence: "medium", awarenessTime: "Before open rebellion", discoveryMethod: "Security reports and arrests", belief: "Resistance is fragmented and containable", objectiveTruth: "The network is coordinated enough to become a strategic threat", visibility: "shared", notes: "Institutional underestimation drives delayed response." }),
  "cassius-darrow-secret": knowledge({ id: "cassius-darrow-secret", observerId: "cassius", subject: { entityType: "character", entityId: "darrow" }, state: "disputed", confidence: "medium", awarenessTime: "Institute period", discoveryMethod: "Behavioral evidence and later revelation", belief: "Darrow's identity is inconsistent with his claimed birth", objectiveTruth: "Darrow is a carved Red", visibility: "private", notes: "This record supports competing versions of when knowledge became certain." }),
  "octavia-lysander": knowledge({ id: "octavia-lysander", observerId: "octavia", subject: { entityType: "character", entityId: "lysander" }, state: "known", confidence: "high", awarenessTime: "Childhood", discoveryMethod: "Dynastic guardianship", belief: "Lysander is a political successor", objectiveTruth: "Lysander is an heir whose choices can restore or transform Gold power", visibility: "private", notes: "A knowledge record tied to succession planning." }),
}
