"use client"

import { createContext, useCallback, useContext, useMemo, useState, type ReactNode } from "react"
import { redRisingDemo, redRisingImage } from "./red-rising-demo-data"

export type SpeciesType = string
export type SpeciesFieldValue = string | string[]
export type SpeciesFieldControl = "text" | "textarea" | "select" | "multi-select"
export type SpeciesFieldSection =
  | "Identity" | "Basic Classification" | "Anatomy and Appearance" | "Sex / Reproduction"
  | "Lifespan and Development" | "Biology / Physiology" | "Abilities / Special Traits"
  | "Culture and Society" | "Habitat and Distribution" | "Origin" | "Relationships with Other Species"
  | "Civilization / Technology" | "Combat" | "Cultural / Historical Significance" | "Population / Status" | "General Notes"

export type SpeciesFieldOption = { value: string; label: string; help?: string }
export type SpeciesFieldDefinition = { id: string; label: string; section: SpeciesFieldSection; control: SpeciesFieldControl; options?: SpeciesFieldOption[]; allowOther?: boolean; placeholder?: string }
const other = (values: SpeciesFieldOption[]) => [...values, { value: "other", label: "Other" }]
const options = (values: string[]) => values.map((value) => ({ value, label: value }))
const area = { identity: "Identity", classification: "Basic Classification", anatomy: "Anatomy and Appearance", reproduction: "Sex / Reproduction", lifespan: "Lifespan and Development", biology: "Biology / Physiology", abilities: "Abilities / Special Traits", culture: "Culture and Society", habitat: "Habitat and Distribution", origin: "Origin", relationships: "Relationships with Other Species", technology: "Civilization / Technology", combat: "Combat", significance: "Cultural / Historical Significance", population: "Population / Status", notes: "General Notes" } as const
const select = (id: string, label: string, section: SpeciesFieldSection, values: string[]): SpeciesFieldDefinition => ({ id, label, section, control: "select", options: other(options(values)), allowOther: true })
const multi = (id: string, label: string, section: SpeciesFieldSection, values: string[]): SpeciesFieldDefinition => ({ id, label, section, control: "multi-select", options: other(options(values)), allowOther: true })
const text = (id: string, label: string, section: SpeciesFieldSection, control: "text" | "textarea" = "textarea"): SpeciesFieldDefinition => ({ id, label, section, control })

export const SPECIES_TYPES = other([
  { value: "humanoid", label: "Humanoid" }, { value: "beast-animal", label: "Beast / Animal" }, { value: "monstrous", label: "Monstrous" },
  { value: "magical-supernatural", label: "Magical / Supernatural" }, { value: "construct", label: "Construct" }, { value: "spirit-ethereal", label: "Spirit / Ethereal" },
  { value: "aquatic", label: "Aquatic" }, { value: "plant-fungal", label: "Plant / Fungal" }, { value: "insectoid-arthropod", label: "Insectoid / Arthropod" },
  { value: "reptilian", label: "Reptilian" }, { value: "avian", label: "Avian" },
])
export function speciesTypeLabel(type: SpeciesType): string { return SPECIES_TYPES.find((option) => option.value === type)?.label ?? type }

export const SPECIES_FIELD_DEFINITIONS: SpeciesFieldDefinition[] = [
  text("alternateNames", "Alternate Names", area.identity, "text"),
  { id: "speciesType", label: "Species Type", section: area.classification, control: "select", options: SPECIES_TYPES, allowOther: true },
  select("sentience", "Sentience", area.classification, ["Non-Sapient", "Sapient", "Variable", "Unknown"]),
  select("intelligence", "Intelligence", area.classification, ["Limited", "Typical", "Highly Intelligent", "Exceptional", "Variable", "Unknown"]),
  text("generalAppearance", "General Appearance", area.anatomy), select("bodyStructure", "Body Structure", area.anatomy, ["Humanoid", "Quadrupedal", "Serpentine", "Avian", "Insectoid / Arthropod", "Aquatic", "Amorphous", "Plant-like", "Mixed / Hybrid"]),
  select("sizeCategory", "Size Category", area.anatomy, ["Tiny", "Small", "Medium", "Large", "Very Large", "Massive", "Variable"]), text("physicalVariation", "Physical Variation", area.anatomy), text("distinctiveFeatures", "Distinctive Features", area.anatomy),
  select("sexStructure", "Sex Structure", area.reproduction, ["Two Sexes", "Multiple Sexes", "Single Sex", "Asexual", "Variable", "Unknown"]), multi("reproduction", "Reproduction", area.reproduction, ["Sexual", "Asexual", "Egg-Laying", "Live Birth", "Spore / Seed Based", "Budding / Division", "Supernatural / Metaphysical", "Multiple Methods", "Unknown"]), text("reproductiveNotes", "Reproductive Notes", area.reproduction),
  select("lifespan", "Lifespan", area.lifespan, ["Very Short", "Short", "Typical", "Long-Lived", "Extremely Long-Lived", "Effectively Ageless", "Immortal", "Variable", "Unknown"]), select("maturation", "Maturation", area.lifespan, ["Rapid", "Typical", "Slow", "Very Slow", "Variable", "Unknown"]), text("lifeStages", "Life Stages", area.lifespan),
  select("diet", "Diet", area.biology, ["Herbivorous", "Carnivorous", "Omnivorous", "Insectivorous", "Photosynthetic", "Mineral / Elemental", "Supernatural / Metaphysical", "Does Not Require Food", "Variable"]), multi("environmentalAdaptation", "Environmental Adaptation", area.biology, ["Terrestrial", "Aquatic", "Aerial", "Underground", "Arctic / Cold", "Desert / Arid", "Tropical", "Temperate", "Multiple Environments"]), text("biologicalTraits", "Biological Traits", area.biology), text("naturalVulnerabilities", "Natural Vulnerabilities", area.biology),
  text("naturalAbilities", "Natural Abilities", area.abilities), text("supernaturalAbilities", "Supernatural / Special Abilities", area.abilities), select("abilityVariation", "Ability Variation", area.abilities, ["Universal", "Common", "Uncommon", "Rare", "Individual", "Conditional", "Variable", "Unknown"]),
  select("socialOrganization", "Social Organization", area.culture, ["Solitary", "Family-Based", "Clan-Based", "Tribal", "Village / Community", "City-Based", "Kingdom / State-Based", "Nomadic", "Caste-Based", "Collective", "Multiple / Variable"]), text("socialStructure", "Social Structure", area.culture), text("culturalTraits", "Cultural Traits", area.culture), text("religion", "Religion / Spirituality", area.culture), text("language", "Language", area.culture, "text"),
  multi("nativeEnvironment", "Native Environment", area.habitat, ["Forest", "Plains", "Mountains", "Desert", "Tundra / Arctic", "Swamp / Wetland", "Coast", "Ocean / Deep Water", "Underground", "Urban", "Multiple Environments"]), text("geographicDistribution", "Geographic Distribution", area.habitat), select("populationDistribution", "Population Distribution", area.habitat, ["Widespread", "Regional", "Localized", "Isolated", "Scattered", "Nomadic", "Unknown"]),
  select("originType", "Origin Type", area.origin, ["Naturally Evolved / Developed", "Created", "Engineered", "Transformed from Another Species", "Supernaturally Created", "Emergent", "Descended from an Earlier Species", "Unknown"]), text("originStory", "Origin Story", area.origin), text("creatorOriginator", "Creator / Originator", area.origin), text("ancestry", "Ancestry", area.origin),
  select("technologicalLevel", "Technological Level", area.technology, ["Primitive", "Pre-Industrial", "Medieval / Feudal", "Early Industrial", "Industrial", "Advanced", "Highly Advanced", "Post-Scarcity / Extraordinary", "Variable", "Unknown"]), text("technologicalCharacteristics", "Technological Characteristics", area.technology), text("commonMaterials", "Common Materials / Resources", area.technology),
  select("combatOrientation", "Combat Orientation", area.combat, ["Generally Non-Combatant", "Defensive", "Hunter / Predator", "Warrior Culture", "Militarized", "Specialized", "Variable", "Unknown"]), text("naturalCombatTraits", "Natural Combat Traits", area.combat), text("typicalCombatMethods", "Typical Combat Methods", area.combat),
  select("historicalSignificance", "Historical Significance", area.significance, ["Minimal", "Local", "Regional", "Major", "World-Historical", "Unknown"]), text("historicalBackground", "Historical Background", area.significance), select("culturalSignificance", "Cultural Significance", area.significance, ["Minimal", "Local", "Regional", "Major Cultural Importance", "Sacred / Religious", "Symbolic", "Unknown"]), text("culturalNotes", "Cultural Notes", area.significance),
  select("populationStatus", "Population Status", area.population, ["Common", "Uncommon", "Rare", "Endangered", "Critically Endangered", "Extinct", "Presumed Extinct", "Unknown"]), text("populationNotes", "Population Notes", area.population), text("additionalInformation", "Additional Information", area.notes),
]
export const SPECIES_SECTIONS: SpeciesFieldSection[] = Object.values(area)

export type SpeciesRelationshipEntityType = "species" | "character" | "organization" | "religion" | "history"
export type SpeciesRelationshipRole = "creator" | "ancestor" | "descendant" | "allied" | "rival" | "related" | "important-history"
export type SpeciesRelationship = { role: SpeciesRelationshipRole; entityType: SpeciesRelationshipEntityType; entityId: string }
export type CanonSpecies = { id: string; name: string; type: SpeciesType; image?: string; summary?: string; fieldValues: Record<string, SpeciesFieldValue>; excludedFieldIds: string[]; relationships: SpeciesRelationship[]; createdAt: number }
export type SpeciesEdit = Partial<Pick<CanonSpecies, "name" | "type" | "image" | "summary" | "fieldValues" | "excludedFieldIds" | "relationships">>
export type SpeciesTemplate = { id: string; name: string; category: string; description: string; values: SpeciesEdit }

const baseValues = (type: string, summary: string, values: Record<string, SpeciesFieldValue> = {}): SpeciesEdit => ({ type, summary, fieldValues: { speciesType: speciesTypeLabel(type), sentience: "Sapient", intelligence: "Typical", ...values } })
const named = (id: string, name: string, category: string, description: string, values: SpeciesEdit): SpeciesTemplate => ({ id, name, category, description, values })
const templateGroups = [
  { category: "Humanoid", names: ["Elf", "High Elf", "Wood Elf", "Dark Elf / Drow", "Orc", "Half-Orc", "Dwarf", "Halfling", "Gnome", "Goblin", "Hobgoblin", "Troll", "Ogre", "Giant", "Half-Giant", "Human"], type: "humanoid", summary: "A broadly humanoid fantasy people template intended for setting-specific editing.", defaults: { bodyStructure: "Humanoid", sizeCategory: "Medium", lifespan: "Typical", socialOrganization: "Family-Based", nativeEnvironment: ["Terrestrial"], originType: "Naturally Evolved / Developed", technologicalLevel: "Variable" } },
  { category: "Fae / Magical", names: ["Fairy", "Faerie", "Pixie", "Dryad", "Nymph", "Satyr", "Centaur", "Selkie"], type: "magical-supernatural", summary: "A magical folk template with supernatural traits left broad for the setting.", defaults: { bodyStructure: "Mixed / Hybrid", sizeCategory: "Variable", lifespan: "Long-Lived", nativeEnvironment: ["Forest", "Multiple Environments"], originType: "Supernaturally Created", supernaturalAbilities: "Supernatural gifts are common in folklore, but their exact nature is setting-dependent.", abilityVariation: "Variable" } },
  { category: "Undead / Supernatural", names: ["Vampire", "Dhampir", "Werewolf / Lycanthrope", "Revenant", "Skeleton", "Zombie", "Lich", "Ghost / Spirit", "Wraith", "Banshee"], type: "magical-supernatural", summary: "A supernatural or transformed being template; specific rules remain editable.", defaults: { bodyStructure: "Humanoid", diet: "Supernatural / Metaphysical", nativeEnvironment: ["Multiple Environments"], originType: "Supernaturally Created", supernaturalAbilities: "The template assumes an extraordinary condition or ability, with exact limits determined by the setting.", abilityVariation: "Variable", naturalVulnerabilities: "Setting-dependent supernatural vulnerabilities." } },
  { category: "Demonic / Celestial", names: ["Demon", "Devil", "Tiefling", "Angel", "Celestial / Divine Being", "Nephilim / Half-Celestial"], type: "magical-supernatural", summary: "A planar, infernal, or divine being template with broad supernatural assumptions.", defaults: { bodyStructure: "Humanoid", lifespan: "Extremely Long-Lived", originType: "Supernaturally Created", supernaturalAbilities: "Planar or divine power is possible; details depend on the setting.", nativeEnvironment: ["Multiple Environments"] } },
  { category: "Aquatic", names: ["Mermaid / Merman", "Siren", "Sea Elf", "Aquatic Humanoid"], type: "aquatic", summary: "An aquatic people template suited to water-adapted societies.", defaults: { bodyStructure: "Aquatic", environmentalAdaptation: ["Aquatic"], nativeEnvironment: ["Ocean / Deep Water", "Coast"], diet: "Omnivorous", originType: "Naturally Evolved / Developed", socialOrganization: "Village / Community" } },
  { category: "Beast / Monstrous", names: ["Minotaur", "Harpy", "Lamia", "Medusa", "Basilisk", "Chimera", "Griffin", "Hippogriff", "Phoenix", "Kraken", "Hydra"], type: "monstrous", summary: "A beast or monstrous species template with iconic anatomy kept adaptable.", defaults: { bodyStructure: "Mixed / Hybrid", sizeCategory: "Large", diet: "Carnivorous", nativeEnvironment: ["Multiple Environments"], combatOrientation: "Hunter / Predator", naturalCombatTraits: "Distinctive anatomy may provide natural defenses or weapons.", originType: "Naturally Evolved / Developed" } },
  { category: "Dragon / Reptilian", names: ["Dragon", "Wyvern", "Draconic Humanoid / Dragonborn", "Kobold", "Lizardfolk", "Serpent Folk"], type: "reptilian", summary: "A reptilian or draconic species template for setting-specific worldbuilding.", defaults: { bodyStructure: "Serpentine", sizeCategory: "Variable", diet: "Carnivorous", nativeEnvironment: ["Multiple Environments"], naturalCombatTraits: "Claws, teeth, scales, or other reptilian adaptations may shape combat.", originType: "Naturally Evolved / Developed", lifespan: "Long-Lived" } },
  { category: "Elemental / Construct / Other", names: ["Elemental", "Djinn / Genie", "Golem", "Homunculus", "Animated Construct", "Plant Person / Treant", "Mushroom / Fungal Folk", "Shapeshifter"], type: "construct", summary: "A nontraditional species template for elemental, constructed, plant, fungal, or mutable beings.", defaults: { bodyStructure: "Amorphous", diet: "Supernatural / Metaphysical", nativeEnvironment: ["Multiple Environments"], originType: "Created", technologicalLevel: "Variable" } },
]
const key = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-")
export const SPECIES_TEMPLATES: SpeciesTemplate[] = templateGroups.flatMap((group) => group.names.map((name) => {
  const lower = name.toLowerCase()
  const overrides: Record<string, SpeciesFieldValue> = lower === "elf" ? { lifespan: "Long-Lived", intelligence: "Highly Intelligent", nativeEnvironment: ["Forest", "Multiple Environments"], naturalAbilities: "Keen senses and a strong affinity with the natural or magical world are common fantasy conventions.", socialOrganization: "Clan-Based" } : lower === "orc" ? { sizeCategory: "Large", diet: "Omnivorous", socialOrganization: "Tribal", combatOrientation: "Warrior Culture", naturalCombatTraits: "Robust physicality and endurance are common archetypal traits." } : lower === "dwarf" ? { sizeCategory: "Small", lifespan: "Long-Lived", socialOrganization: "Clan-Based", nativeEnvironment: ["Mountains", "Underground"], technologicalLevel: "Medieval / Feudal", technologicalCharacteristics: "Craftsmanship, mining, metallurgy, and durable engineering are common archetypal associations." } : lower === "dragon" ? { bodyStructure: "Mixed / Hybrid", sizeCategory: "Massive", lifespan: "Extremely Long-Lived", intelligence: "Exceptional", supernaturalAbilities: "Flight, elemental expression, and extraordinary perception are common broad dragon conventions.", combatOrientation: "Hunter / Predator", nativeEnvironment: ["Mountains", "Multiple Environments"] } : lower === "vampire" ? { lifespan: "Effectively Ageless", diet: "Supernatural / Metaphysical", supernaturalAbilities: "Enhanced senses, physical ability, and transformation are common folklore conventions; exact powers vary.", naturalVulnerabilities: "Folkloric vulnerabilities vary widely by setting and should be edited.", originType: "Transformed from Another Species" } : {}
  return named(key(name), name, group.category, group.summary, baseValues(group.type, group.summary, { ...Object.fromEntries(Object.entries(group.defaults).filter(([, value]) => value !== undefined)) as Record<string, SpeciesFieldValue>, ...overrides }))
}))
export const SPECIES_TEMPLATES_WITH_ARCHETYPES = [...SPECIES_TEMPLATES, named("wizard-witch", "Wizard / Witch", "Elemental / Construct / Other", "A magical humanoid archetype, not a claim that magic-users are universally a biological Species.", baseValues("humanoid", "A magical humanoid archetype rather than a universal biological Species; edit the record for the setting.", { bodyStructure: "Humanoid", originType: "Emergent", supernaturalAbilities: "Learned or inherited magical practice; exact rules are setting-dependent.", abilityVariation: "Individual", socialOrganization: "Multiple / Variable" }))]

type SpeciesCanonContextValue = { species: Record<string, CanonSpecies>; getSpecies: (id: string | null | undefined) => CanonSpecies | null; updateSpecies: (id: string, patch: SpeciesEdit) => void; addSpecies: (patch: SpeciesEdit) => string }
const SpeciesCanonContext = createContext<SpeciesCanonContextValue | null>(null)
function makeId(name: string, existing: Record<string, CanonSpecies>): string { const base = name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "species"; let id = base; let suffix = 2; while (existing[id]) id = `${base}-${suffix++}`; return id }
export function SpeciesCanonProvider({ children }: { children: ReactNode }) {
  const [species, setSpecies] = useState<Record<string, CanonSpecies>>(() =>
    Object.fromEntries(
      Object.entries(redRisingDemo.species as unknown as Record<string, CanonSpecies>).map(([id, record]) => [id, { ...record, image: redRisingImage("species", id) }]),
    ),
  )
  const getSpecies = useCallback((id: string | null | undefined) => (id ? species[id] ?? null : null), [species])
  const updateSpecies = useCallback((id: string, patch: SpeciesEdit) => setSpecies((previous) => { const existing = previous[id]; if (!existing) return previous; return { ...previous, [id]: { ...existing, ...patch, name: patch.name?.trim() || existing.name, fieldValues: patch.fieldValues ? { ...existing.fieldValues, ...patch.fieldValues } : existing.fieldValues, excludedFieldIds: patch.excludedFieldIds ? [...new Set(patch.excludedFieldIds)] : existing.excludedFieldIds, relationships: patch.relationships ?? existing.relationships } } }), [])
  const addSpecies = useCallback((patch: SpeciesEdit) => { let newId = ""; setSpecies((previous) => { newId = makeId(patch.name?.trim() || "Unnamed Species", previous); return { ...previous, [newId]: { id: newId, name: patch.name?.trim() || "Unnamed Species", type: patch.type ?? "other", image: patch.image, summary: patch.summary, fieldValues: patch.fieldValues ?? {}, excludedFieldIds: patch.excludedFieldIds ?? [], relationships: patch.relationships ?? [], createdAt: Date.now() } } }); return newId }, [])
  const value = useMemo(() => ({ species, getSpecies, updateSpecies, addSpecies }), [species, getSpecies, updateSpecies, addSpecies])
  return <SpeciesCanonContext.Provider value={value}>{children}</SpeciesCanonContext.Provider>
}
export function useSpeciesCanon(): SpeciesCanonContextValue { const context = useContext(SpeciesCanonContext); if (!context) throw new Error("useSpeciesCanon must be used within a SpeciesCanonProvider"); return context }
